# Quantum interference

> About complex numbers, called probability amplitudes, that, unlike probabilities, can cancel each other out, leading to quantum interference and qualitatively new ways of processing information.

The classical theory of computation does not usually refer to physics.
Pioneers such as Alan Turing, Alonzo Church, Emil Post and Kurt Gödel managed to capture the correct classical theory by intuition alone and, as a result, it is often falsely assumed that its foundations are self-evident and purely abstract.
They are not!^[Computation is a physical process. Computation is a physical process. Computation is ...]

The concepts of information and computation can be properly formulated only in the context of a physical theory --- information is stored, transmitted and processed always by _physical_ means.
Computers are physical objects and computation is a physical process.
Indeed, any computation, classical or quantum, can be viewed in terms of physical experiments, which produce **outputs** that depend on initial preparations called **inputs**.
Once we abandon the classical view of computation as a purely logical notion independent of the laws of physics it becomes clear that whenever we improve our knowledge about physical reality, we may also gain new means of computation.
Thus, from this perspective, it is not very surprising that the discovery of quantum mechanics in particular has changed our understanding of the nature of computation.
In order to explain what makes quantum computers so different from their classical counterparts, we begin with the rudiments of quantum theory.



## Two basic rules



## Quantum interference (the failure of probability theory)



## Superpositions



## Interferometers



## Qubits, gates, and circuits



## Quantum decoherence



## Computation: deterministic, probabilistic, and quantum



## Computational complexity



## Outlook



## Notes and Exercises



## Supplement: Physics against logic, via beamsplitters



## Supplement: Quantum interference revisited (still about beamsplitters)
