# Quantum entanglement {#chapter5}

> On ... **!!!TODO!!!**

We now know everything we need to know about a single qubit and its quantum behaviour.
But if we want to understand quantum computation --- a complicated quantum interference of many interacting qubits --- then we will need few more mathematical tools.
Stepping up from one qubit to two or more is a bigger leap than you might expect.
Already, with just two qubits, we will encounter the remarkable phenomenon of quantum entanglement and have a chance to discuss some of the most puzzling features of quantum theory that took people decades to understand.





## A small history

The notion of **quantum entanglement** was the subject of many early debates that focused on the meaning of quantum theory.
Back in the 1930s, Albert Einstein, Niels Bohr, Werner Heisenberg, and Erwin Schrodinger (to mention just the usual suspects) were trying hard to understand its conceptual consequences.^[E. Schrodinger, Discussion of probability relations between separated system, _Mathematical Proceedings of the Cambridge Philosophical Society_ **31** (1935), pp. 555--563.]
Einstein, the most sceptical of them all, claimed that it was pointing toward the fatal flaw in quantum theory, and referred to it as "_spooky action-at-a-distance_".
In contrast, Schrödinger was much more prepared to accept quantum theory exactly as it was formulated, along with all its predictions, no matter how weird they might be.
In his 1935 paper, which introduced quantum entanglement, he wrote "I would not call it _one_ but rather _the_ characteristic trait of quantum mechanics, the one that enforces its entire departure from classical lines of thought".
Today we still talk a lot about quantum entanglement, but more often it is viewed as a physical resource which enables us to communicate with perfect security, build very precise atomic clocks, and even teleport small quantum objects!
But what exactly is quantum entanglement?





## One, two, many...

In classical physics, the transition from a single object to a composite system of many objects is trivial: in order to describe the state of, say, 42 objects at any given moment of time, it is sufficient to describe the state of each of the objects separately.
Indeed, the classical state of 42 point-like particles is described by specifying the position and the momentum of each particle.

::: {.idea data-latex=""}
In the _classical_ world, "the whole is the sum of its parts", but the _quantum_ world is very different.
:::

Consider, for example, a pair of qubits.
Suppose that each one is described by a state vector: the first one by $\ket{a}$, and the second one by $\ket{b}$.
One might therefore think that the most general state of the two qubits should be represented by a pair of state vectors, $\ket{a}\ket{b}$, with one for each qubit.
Indeed, such a state is certainly possible, but there are other states that _cannot_ be expressed in this form.
In order to write down the most general state of two qubits we first focus on the basis states.

For a single qubit we have been using the standard basis $\{\ket{0},\ket{1}\}$.
For two qubits we may choose the following as our standard basis states:^[It looks like we are defining some sort of "multiplication rule" for kets here, saying that $\ket{a}\ket{b}:=\ket{ab}$. This is indeed the case, but to talk about this properly we need to introduce the idea of **tensor products** (which we do very soon).]
$$
  \begin{array}{cc}
    \ket{00} \equiv \ket{0}\ket{0}
    & \ket{01} \equiv \ket{0}\ket{1}
  \\\ket{10} \equiv \ket{1}\ket{0}
    &\ket{11} \equiv \ket{1}\ket{1}.
  \end{array}
$$
Within each ket, the first symbol refers to the first qubit, and the second to the second, and we have tacitly assumed that we can distinguish the two qubits by their location, or some other means.
Now, the most general state of the two qubits is a normalised linear combination of these four basis states, i.e. a vector of the form
$$
  \ket{\psi}
  = c_{00}\ket{00} + c_{01}\ket{01} + c_{10}\ket{10} + c_{11}\ket{11}.
$$
Physical interpretation aside, let us count how many real parameters are needed to specify this state.
Six, right?
We have four complex numbers (eight real parameters) restricted by the normalisation condition, along with the fact that states differing only by a global phase factor are equivalent, which leaves us with six real parameters.
Now, by the same line of argument, we need only two real parameters to specify the state of a single qubit, and hence need four real parameters to specify any state of two qubits of the form $\ket{a}\ket{b}$.
So it cannot be the case that every state of two qubits can be expressed as a pair of states $\ket{a}\ket{b}$, simply for "dimension reasons".

For example, compare the two states of two qubits,
$$
  \begin{gathered}
    \frac{1}{\sqrt 2}\ket{00} + \frac{1}{\sqrt 2}\ket{01}
  \\\mbox{and}
  \\\frac{1}{\sqrt 2}\ket{00} + \frac{1}{\sqrt 2}\ket{11}.
  \end{gathered}
$$
The first one is **separable**, i.e. we can view it as a pair of state vectors where each one pertains to one of the two qubits:
$$
  \frac{1}{\sqrt 2}\ket{00} + \frac{1}{\sqrt 2}\ket{01}
  = \underbrace{\vphantom{\frac{1}{\sqrt 2}}\ket{0}}_{\text{qubit 1}}
  \;\;
  \underbrace{\frac{1}{\sqrt 2}(\ket{0}+\ket{1})}_{\text{qubit 2}},
$$
The second state, however, does _not_ admit such a decomposition: there do _not_ exist any $\psi_1,\psi_2$ such that
$$
  \frac{1}{\sqrt 2}\ket{00} + \frac{1}{\sqrt 2}\ket{11}
  =
  \ket{\psi_1}\ket{\psi_2}
$$
and so we say that it is an **entangled** state.
Informally, any bipartite state that cannot be viewed as a pair of two states pertaining to the constituent subsystems is said to be entangled.

With this discussion in our minds, we can now give more formal account of the states of composite quantum systems.





## Quantum theory, formally (continued)

Recalling [Chapter 4](#chapter4), where we said that we were missing a key part of the formalism of quantum theory, we can now fill in this hole.
Our mathematical formalism of choice behind the quantum theory of composite systems is based on the **tensor product** of Hilbert spaces.

### Tensor products

Let the states of some system $\mathcal{A}$ be described by vectors in an $n$-dimensional Hilbert space $\mathcal H_A$, and the states of some system $\mathcal{B}$ by vectors in an $m$-dimensional Hilbert space $\mathcal H_B$.
The combined system of $\mathcal{A}$ and $\mathcal{B}$ is then described by vectors in the $(nm)$-dimensional **tensor product space** $\mathcal{H}_A\otimes\mathcal{H}_B$.
Given bases $\{\ket{a_1},\ldots,\ket{a_n}\}$ of $\mathcal H_A$ and $\{\ket{b_1},\ldots,\ket{b_m}\}$ of $\mathcal H_B$, we form a basis of the tensor product by taking the ordered pairs $\ket{a_i}\otimes\ket{b_j}$, for $i=1,\ldots,n$ and $j=1,\ldots,m$.
The tensor product space $\mathcal{H}_A\otimes\mathcal{H}_B$ then consists of all linear combination of such tensor product basis vectors:^[If the bases $\{\ket{a_i}\}$ and $\{\ket{b_j}\}$ are orthonormal then so too is the tensor product basis $\{\ket{a_i}\otimes\ket{b_j}\}$.]
\begin{equation}
  \ket{\psi}
  = \sum_{ij} c_{ij}\ket{a_i}\otimes\ket{b_j}.
(\#eq:bipartite)
\end{equation}

The tensor product operation $\otimes$ is distributive:
$$
  \begin{gathered}
    \ket{a} \otimes \left( \beta_1\ket{b_1} + \beta_2\ket{b_2} \right)
    = \beta_1\ket{a}\otimes\ket{b_1} + \beta_2\ket{a}\otimes\ket{b_2}
  \\\left( \alpha_1\ket{a_1} + \alpha_2\ket{a_2} \right) \otimes \ket{b}
    = \alpha_1\ket{a_1}\otimes\ket{b} + \alpha_2\ket{a_2}\otimes\ket{b}.
  \end{gathered}
$$
The tensor product of Hilbert spaces is again a Hilbert space: the inner products on $\mathcal{H}_A$ and $\mathcal{H}_B$ give a natural inner product on $\mathcal{H}_A\otimes\mathcal{H}_B$, defined for any two product vectors by^[The bra corresponding to the tensor product state $\ket{a}\otimes\ket{b}$ is written as $(\ket{a}\otimes\ket{b})^\dagger = \bra{a}\otimes\bra{b}$, where the order of the factors on either side of $\otimes$ does not change when the dagger operation is applied.]
$$
  \left( \bra{a'}\otimes\bra{b'} \right) \left( \ket{a}\otimes\ket{b} \right)
  = \braket{a'|a}\braket{b'|b}
$$
and extended by linearity to sums of tensor products of vectors, and by associativity^[$({\mathcal{H}}_a \otimes {\mathcal{H}}_b)\otimes {\mathcal{H}}_c = {\mathcal{H}}_a \otimes ({\mathcal{H}}_b\otimes {\mathcal{H}}_c)$.] to any number of subsystems.

Some joint states of $\mathcal{A}$ and $\mathcal{B}$ can be expressed as a single tensor product, say $\ket{\psi}=\ket{a}\otimes\ket{b}$ (often written as $\ket{a}\ket{b}$, or $\ket{a, b}$, or even $\ket{ab}$), meaning that the subsystem $\mathcal{A}$ is in state $\ket{a}$, and the subsystem $\mathcal{B}$ in state $\ket{b}$.
If we expand $\ket{a}=\sum_i\alpha_i\ket{a_i}$ and $\ket{b}=\sum_i\beta_j\ket{b_j}$, then $\ket{\psi}=\sum_{ij}\alpha_i\beta_j\ket{a_i}\otimes\ket{b_j}$ and we see that, for all such states, the coefficients $c_{ij}$ in Equation \@ref(eq:bipartite) are of a rather special form:
$$
  c_{ij} = \alpha_i\beta_j.
$$
We call such states **separable** (or just **product states**).
States that are not separable are said to be **entangled**.

A useful fact about tensor products is that $\lambda a\otimes b = a\otimes\lambda b$ (where $a$ and $b$ are vectors, and $\lambda$ is a scalar).
This means that we don't need to worry about brackets and write something like $\lambda(a\otimes b)$.

We will also need the concept of the tensor product of two operators.
If $A$ is an operator on $\mathcal{H}_A$ and $B$ an operator on $\mathcal{H}_B$, then the tensor product operator $A\otimes B$ is an operator on $\mathcal{H}_A\otimes\mathcal{H}_B$ defined by its action on product vectors via
$$
  (A\otimes B)(\ket{a}\otimes\ket{b}) = (A\ket{a})\otimes (B\ket{b})
$$
and with its action on all other vectors determined by linearity:
$$
  A\otimes B \left( \sum_{ij} c_{ij}\ket{a_i}\otimes\ket{b_j} \right)
  = \sum_{ij}c_{ij} A\ket{a_i}\otimes B\ket{b_j}.
$$






## Back to qubits

Let's see how this formalism works for qubits.
The $n$-fold tensor product of vectors from the standard basis $\{\ket{0},\ket{1}\}$ represent binary strings of length $n$.
For example, for $n=3$,^[We often drop the $\otimes$ symbol, especially when we deal with the standard tensor product basis. For example, a state of a quantum register composed of four qubits holding the binary string $1001$ may be written as $\ket{1}\otimes\ket{0}\otimes\ket{0}\otimes\ket{1}$, as $\ket{1}\ket{0}\ket{0}\ket{1}$, or even simply as $\ket{1001}$.]
$$
  \begin{aligned}
    \ket{0}\otimes\ket{1}\otimes\ket{1}
    & \equiv \ket{011}
  \\\ket{1}\otimes\ket{1}\otimes\ket{1}
    & \equiv \ket{111}.
  \end{aligned}
$$
A _classical_ register composed of three bits can store _only one_ of these two binary strings at any time; a _quantum_ register composed of three qubits can store _both of them_ in a superposition.

Indeed, if we start with the state $\ket{011}$ and apply the Hadamard gate to the first qubit (which is the same as applying $H\otimes\id\otimes\id$), then, given that linear combinations distribute over tensor products, we obtain^[We often simply write $H\otimes H\otimes H$ as $H^{\otimes 3}$.]
$$
  \begin{aligned}
    \ket{011}
    \longmapsto
    &\frac{1}{\sqrt2} \big(\ket{0} + \ket{1}\big) \otimes\ket{1}\otimes\ket{1}
  \\\equiv
    &\frac{1}{\sqrt2} \big(\ket{011} + \ket{111}\big).
  \end{aligned}
$$
In fact, we can even prepare this register in a superposition of all eight possible binary strings: if we apply the tensor product operation $H\otimes H\otimes H$ to the state $\ket{0}\otimes\ket{0}\otimes\ket{0} = \ket{000}$ then we get

```{r,engine='tikz',engine.opts=list(template="tikz2pdf.tex"),fig.width=6}
\begin{equation*}
  \left.
  \begin{quantikz}
    \lstick{$\ket{0}$}
    & \gate{H}
    & \qw \rstick{$\frac{\ket{0}+\ket{1}}{\sqrt2}$}
  \\\lstick{$\ket{0}$}
    & \gate{H}
    & \qw \rstick{$\frac{\ket{0}+\ket{1}}{\sqrt2}$}
  \\\lstick{$\ket{0}$}
    & \gate{H}
    & \qw \rstick{$\frac{\ket{0}+\ket{1}}{\sqrt2}$}
  \end{quantikz}
  \right\}
  =
  \frac{1}{2^{3/2}}
  \left\{
    \begin{array}{r}
      \ket{000} + \ket{001} + \ket{010} + \ket{011}
    \\ + \ket{100} + \ket{101} + \ket{110} + \ket{111}
    \end{array}
  \right\}.
\end{equation*}
```

The resulting state is exactly a superposition of all binary string of length 3, and can also be written as
$$
  \frac{1}{\sqrt2} \big(\ket{0} + \ket{1}\big)
  \otimes
  \frac{1}{\sqrt2} \big(\ket{0} + \ket{1}\big)
  \otimes
  \frac{1}{\sqrt2} \big(\ket{0} + \ket{1}\big).
$$

In general, the tensor product operation $H^{\otimes n}$, which means "apply the Hadamard gate to each of your $n$ qubits", is known as the **Hadamard transform**, and it maps product states to product states.
Like the Hadamard gate in the typical quantum interference circuit, the Hadamard transform opens and closes a multi-qubit interference.






## Separable or entangled?










## Why qubits, subsystems, and entanglement?

One question that is rather natural to ask at this point is the following:

> If entanglement is so fragile and difficult to control, then why bother?
> Why not perform the whole computation in one physical system that has as many quantum states as we normally have labels for the states of qubits, so that we can label these quantum states in the same way as we normally label the qubits, and give _them_ computational meaning?

This suggestion, although possible, gives a very inefficient way of representing data (it is describing the **unary encoding**).
For serious computations _we need subsystems_.
Here is why.

Suppose you have $n$ physical objects, and each object has $k$ distinguishable states.
If you can access each object _separately_ and put it into any of the $k$ states, then, with only $n$ operations, you can prepare any of the $k^{n}$ different configurations of the combined systems.
Without any loss of generality, let us take $k=2$ and refer to each object of this type as a **physical bit**.
We label the two states of a physical bit as $0$ and $1$.
Any collection of $n$ physical bits can be prepared in $2^{n}$ different configurations, which can be used to store up to $2^{n}$ messages/binary strings/different numbers.
In order to represent numbers from $0$ to $N-1$ we just have to choose $n$ such that $N\leq 2^n$.

Suppose the two states in the physical bit are separated by the energy difference $\Delta E$.
Then a preparation of any particular configuration will cost no more than $E=n \Delta E=(\log_2 N)\Delta E$ units of energy.

In contrast, if we choose to encode $N$ configurations into one chunk of matter, say, into the first $N$ energy states of a single harmonic oscillator with the interstate energy separation $\Delta E$ then, in the worst case, one has to use $E=N\Delta E$ units of energy, e.g. to go from the ground state (labelled as $0$) to the most excited state (labelled as $N$).
For large $N$ this gives an exponential gap in the energy expenditure between the binary encoding using physical bits and unary encoding, using energy levels of harmonic oscillators.

One can, of course, try to switch from harmonic oscillators to quantum systems which have a finite spread in the energy spectrum.
For example, by operating on the energy states of the hydrogen atom one can encode any number from $0$ to $N-1$, and one is guaranteed not to spend more than $E_{\mathrm{max}}=$ $13.6\,\mathrm{eV}$ (otherwise the atom is ionised).
The snag is that, in this case, some of the electronic states will be separated by the energy difference to the order of $E_{\mathrm{max}}/N$, and to drive the system selectively from one state to another one has to tune into the frequency $E_{\mathrm{max}}/\hbar N$, which requires a sufficiently long wave-packet (so that the frequency is well defined), and consequently the
interaction time is of order $N(\hbar/E_{\mathrm{max}})$.

That is, we have to trade energy for time.

It turns out that whichever way we try to represent the number $N$ using the unary encoding (i.e. using $N$ different states of a single chunk of matter), we end up depleting our physical resources (such as energy, time, space) at a much greater rate than in the case when we use subsystems.
This plausibility argument indicates that, for efficient processing of information, the system must be divided into subsystems --- for example, into physical bits.
