# Quantum channels (or CP maps) {#chapter10}

> About linear transformations --- often called **quantum channels**, **quantum operations**, or **superoperators** --- that map density operators to density operators. Mathematically, such objects are known as **completely positive trace-preserving maps**. Be prepared for some name dropping; you will hear about Karl Kraus, Woody Stinespring, Andrzej Jamiołkowski, and Man-Duen Choi. To be sure, knowing names will not give you more insights, but at least you will not be intimidated when you hear about the **Stinespring** and the **Kraus representations**, the **Jamiołkowski isomorphism**, or the **Choi matrix**. 

In quantum information science (and in life) we often divide the world into two parts: things we can control and everything else.
Things we can control (at least with some precision), such as a bunch of ions in an ion trap, will now acquire a generic name -- the **system** -- and the "everything else" part will be called the **environment**.
The joint evolution of the system and the environment is unitary, but the system _alone_ may deviate from the unitary evolution due to the entangling interactions with the environment.
What does this non-unitary quantum evolution look like?

Mathematically speaking^[Recall that, given a pair of Hilbert spaces $\mathcal{H}_A$ and $\mathcal{H}_B$, we denote the set of (bounded) linear operators from $\mathcal{H}_A$ to $\mathcal{H}_B$ by $\mathcal{B}(\mathcal{H}_A,\mathcal{H}_B)$. The shorthand $\mathcal{B}(\mathcal{H})$ is used to denote $\mathcal{B(H,H)}$. For example, $\rho\in\mathcal{B}(\mathcal{H})$ is a density operator on $\mathcal{H}$.], we want to characterise **physically admissible** maps
$$
  \mathcal{B}\colon \mathcal{B}(\mathcal{H}) \to \mathcal{B}(\mathcal{H}')
$$
that map density operators to density operators.
We will call them **quantum channels**.
Here, $\mathcal{H}$ and $\mathcal{H}'$ are the Hilbert spaces associated with the input and the output, respectively (these two spaces may be of different dimensions: $\dim\mathcal{H}=d$ and $\dim\mathcal{H}'=d'$, with $d$ not necessarily equal to $d'$).
It is not a trivial task, since some operations (such as the matrix transpose) turn density matrices into seemingly legal density matrices, and yet they are _not_ physically admissible.
We want to understand why.

There are essentially two approaches to characterising quantum channels. Let us call them **constructive** and **axiomatic**.
In the constructive approach (much favoured by physicists) we assume that, in the quantum world, there are only unitary evolutions, and that _non_-unitary evolutions of subsystems are induced by unitary evolutions of _larger_ systems.
We can view them as the result of adding or removing physical systems that participate in unitary evolutions.
In particular, _any_ quantum channel can be constructed by taking a physical system in state $\rho$, combining it with an auxiliary system (e.g. the environment) in some fixed quantum state, applying a unitary transformation to the combined system, and then discarding everything that is of no interest to us.

In the axiomatic approach we proceed as mathematicians usually do.
We refer to quantum theory for inspiration, scratch our heads, and list all the desired properties that a map should have in order to be called an admissible quantum operation.
This way we define **completely positive trace-preserving** (CPTP) maps.

In the end, you will be relieved to learn, the two approaches are equivalent, leading to the same mathematical formalism.
This equivalence is often goes by the name of the **Stinespring dilation theorem**^[[William Forrest "Woody" Stinespring](https://en.wikipedia.org/wiki/W._Forrest_Stinespring) (1929--2012) was an American mathematician specialising in operator theory.], which says that the CPTP maps are exactly the maps which can be constructed from unitary evolutions by adding and removing subsystems.
