## Using the e-book {-}

<!-- TO-DO: print a warning if javascript is disabled in their browser, saying precisely what it is used for -->
This book has some functionality unique to the online (as opposed to the PDF) version, accessed using the toolbar along the top of the window.
From left to right, the icons have the following use:

- <i class="fa fa-align-justify"></i> — Hide/show the table of contents
- <i class="fa fa-search"></i> — Search within the text of the book
- <i class="fa fa-font"></i> — Change font size, font face, and toggle dark mode
- <i class="fa fa-code"></i> — View the source file of the current chapter on GitHub^[The GitHub-savvy of you can use this to create issues pointing out typos, mistakes, etc.]
- <i class="fa fa-file-pdf-o"></i> — Open the PDF version of the book in a new tab

The online version also has [the accompanying lecture videos](https://www.youtube.com/playlist?list=PLkespgaZN4gmu0nWNmfMflVRqw0VPkCGH) embedded from YouTube.
These videos are hidden by default, but can be shown by clicking on the title next to the <i class="fa fa-video-camera"></i> icon, wherever one appears.
The order of the videos generally differs from that of the written notes, so we have made our best efforts to include them in an order which makes sense relative to the chapters here.
For those wishing to really get familiar with this subject, we recommend separately watching the lecture videos following the order in [the linked playlist](https://www.youtube.com/playlist?list=PLkespgaZN4gmu0nWNmfMflVRqw0VPkCGH).

You will also see the <i class="fa fa-search-plus"></i> icon in certain places.
Clicking on these will display one of the technical asides mentioned in the introduction.

If a link has the <a class="external-link"></a> icon after it then it points to a webpage *outside* this book, otherwise it is an internal link to another section within this book.

There are also some keyboard shortcuts:

- jump between sections with `←` and `→`
- toggle the table of contents with `s`
- open the search bar with `f`, step through results with `Enter`, and stop searching with `Esc`
