#!/bin/bash


# 1. Check we're in the base directory
if [[ `basename "$PWD"` != "qubit.guide" ]]; then
    echo "Script must be run from the main qubit.guide directory" >&2
    exit 1
else
    echo "Building book..."
fi


# 2. Build the various versions of the book

## Web
R -e "bookdown::render_book('index.Rmd','bookdown::gitbook',config_file='_bookdown.yml')"
## A4 PDF
R -e "bookdown::render_book('index.Rmd','bookdown::pdf_book',config_file='_bookdown.yml')"
# to-do: rename resulting files
## Small book PDF
# R -e "bookdown::render_book('index.Rmd','bookdown::pdf_book',config_file='_bookdown.yml',output_options=list(template='latex-template-6x9.tex'))"
# to-do: rename resulting files


# 3. Post-build changes (i.e. messy hacks)

# Change the "View Source" icon from an eye to "</>"
find . -type f -exec sed -i 's/fa-eye/fa-code/g' {} +
