#!/bin/bash


# 1. Check we're in the base directory

if [[ `basename "$PWD"` != "qubit.guide" ]]; then
    echo "Script must be run from the main qubit.guide directory" >&2
    exit 1
else
    echo "Building book..."
fi


# 2. Delete previous build

R -e "bookdown::clean_book(TRUE)"


# 3. Build the various versions of the book

## Web
R -e "bookdown::render_book('index.Rmd','bookdown::gitbook',config_file='_bookdown.yml')"
## A4 PDF
R -e "bookdown::render_book('index.Rmd','bookdown::pdf_book',config_file='_bookdown.yml')"
# to-do: rename resulting files
## Small book PDF
# R -e "bookdown::render_book('index.Rmd','bookdown::pdf_book',config_file='_bookdown.yml',output_options=list(template='latex-template-6x9.tex'))"
# to-do: rename resulting files


# 4. Post-build changes (i.e. messy hacks)

# Replace some gitbook js files with our custom version
cp web/plugin-bookdown.js book/libs/gitbook-2.6.7/js/plugin-bookdown.js
cp web/plugin-fontsettings.js book/libs/gitbook-2.6.7/js/plugin-fontsettings.js
