# Quantum channels {#chapter7}

> Quantum evolution of any *isolated* system is unitary but its constituent parts may evolve in a more complicated way. In this chapter we will go beyond unitary evolutions and describe physically realisable transformations of density operators, called quantum channels. Be prepared for some name dropping; you will hear about Karl Kraus, Woody Stinespring, Andrzej Jamiołkowski and Man-Duen Choi. To be sure, knowing names will not give you more insights, but at least you will not be intimidated when you hear about the **Stinespring** and the **Kraus representations**, the **Jamiołkowski isomorphism**, or the **Choi matrix**.

We discussed how entanglement forced us to describe quantum states of open quantum systems (ones which are part of a larger system) in terms of density operators.
In this chapter we will describe how open systems evolve.
The question we are asking here is: what are the most general physically admissible transformations of density operators?
At the fundamental level --- and this should be your quantum mantra^[...there is only one unitary evolution, there is only one unitary evolution, there only one unitary evolution... ...and everything else is cheating] --- there is *only one* unitary evolution, and if there is any other evolution then it has to be derived from a unitary evolution.
From this perspective, any non-unitary evolution of an open system is induced by a unitary evolution of a larger system.
But how?
The short answer is: by adding (tensoring) and removing (partial trace) physical systems.
A typical combination of these operations is shown in the following diagram:

```{r,engine='tikz',engine.opts=list(template="tikz2pdf.tex"),fig.width=3}
\begin{quantikz}
  \lstick{fixed state $\ket{a}$}
  & \gate[wires=2]{U}
  & \rstick{discard} \qw
\\\lstick{input $\rho$}
  &
  & \rstick{$\rho'$ output } \qw
\end{quantikz}
```

First, we prepare our system of interest in an input state $\rho$.
Then we dilate the system by "adding" (or "taking into account") an auxiliary system^[Depending on the context, the auxiliary system is either called the **ancilla** (usually when we can control it) or the **environment** (usually when we cannot control it).] which is large enough to include everything our system will interact with, and also large enough to be in a pure state $\ket{a}$.
Mathematically, we do this by tensoring the input state $\rho$ with $\proj{a}$ to obtain $\proj{a}\otimes\rho$ (here we place the auxiliary system first and our system of interest second).
The dilated system is assumed to be closed so that it undergoes some unitary evolution $U$.
After all the interactions have taken place, we *trace out* the auxiliary system, turning the joint state $U\proj{a}\otimes\rho U^\dagger$ of the dilated system into the final state of our system of interest: the output state $\rho'$.
The net effect of this composition, as we shall see in a moment, is the input-output transformation which can be written, as long as the initial state of the auxiliary system in *not* correlated with the input state, in a nice compact way:
$$
  \rho\longmapsto\rho' = \sum_i E_i\rho E_i^\dagger
$$
where the $E_i$ are some operators that satisfy $\sum_i E_i^\dagger E_i=\id$.
This linear map is called a **completely positive trace preserving map**, or, in the parlance of quantum information science, a **quantum channel**.
We will elaborate on the mathematics behind quantum channels shortly, but for now let us only check the essential properties, i.e. that this map preserves both trace and positivity (as its name suggests).

- Trace preserving: since the trace is linear, invariant under cyclic permutations of operators, and we ask that $\sum_i E_i^\dagger E_i=\id$, we see that
    $$
      \tr \left(\sum_k E_k\rho E_k^\dagger\right)
      = \tr \left(\sum_k E^\dagger_k E_k \rho\right)
      = \tr\rho.
    $$
- Positivity preserving: since $\rho$ is a positive^[Recall that an operator is positive if and only if it can be written in the form $XX^\dagger$ for some $X$ (here $X=E_k\sqrt{\rho}$). Also, the sum of positive operators is again a positive operator.] (semi-definite) operator, and so is $\sqrt{\rho}$, we see that
    $$
      \sum_k E_k\rho E_k^\dagger
      = \sum_k (E_k\sqrt{\rho})(\sqrt{\rho} E_k^\dagger).
    $$

These conditions are certainly *necessary* if we want to map density operators into legal density operators, but we shall see in a moment that they are not *sufficient*: quantum channels are not just positive maps, they are **completely** positive maps.
We will discuss their special properties, describe the most common examples, and, last but not least, specify when the action of quantum quantum channels can be reversed, or corrected, so that we can recover the original input state.
This will set the stage for our subsequent discussion of quantum error correction.


## Random unitaries

As a first step toward understanding the quantum description of an evolving open system, consider a "two-qubit universe" in which we observe *only one* of the qubits.
Let us revisit the controlled-$\texttt{NOT}$ gate, in which two qubits undergo the unitary transformation
$$
  U
  = \proj{0}\otimes\id +\proj{1}\otimes X
  = \diag{\id}{X}
$$
and let us focus on the transformation of the target qubit alone.
We know that it depends on the state of the control qubit:

- if the input state of the control qubit is $\ket{0}$, the target qubit evolves unitarily according to the identity operator $\id$;
- if the input state of the control qubit is $\ket{1}$, the target qubit evolves unitarily according to the bit flip operator $X$;
- but for input states of the control that are superpositions of $\ket{0}$ and $\ket{1}$ the evolution of the target qubit is *not* unitary.

To justify this last point, note that, if the control qubit is in the state $\alpha_0\ket{0}+\alpha_1\ket{1}$ and the target qubit is in some state $\ket{\psi}$, then the output state can be written as
$$
  \alpha_0\ket{0}\otimes\id\ket{\psi} + \alpha_1\ket{1}\otimes X\ket{\psi}
$$
which shows that the control and the target become entangled.
The target qubit alone ends up in the statistical mixture of states $\ket{\psi}$ (with probability $|\alpha_0|^2$) and $X\ket{\psi}$ (with probability $|\alpha_1|^2$).
This can be easily verified by expressing the above output state of the two qubits as the density matrix
$$
  \begin{aligned}
    & |\alpha_0|^2\proj{0}\otimes \id\proj{\psi}\id
    + |\alpha_1|^2\proj{1}\otimes X\proj{\psi}X
  \\+& \alpha_0\alpha_1^\star\ket{0}\bra{1} \otimes \id\proj{\psi}X
    + \alpha_0^\star\alpha_1\ket{1}\bra{0} \otimes X\proj{\psi}\id
  \end{aligned}
$$
and then tracing over the control qubit, which gives^[Recall that, for the basis states, $\tr\ket{i}\bra{j}=\braket{i}{j}=\delta_{ij}$.]
$$
  |\alpha_0|^2 \id\proj{\psi}\id
  + |\alpha_1|^2 X\proj{\psi} X. 
$$
We can then say that the input state of the target qubit evolves either according to the identity operator (with probability $|\alpha_0|^2$) or according to the operator $X$ (with probability $|\alpha_1|^2$).

This argument works even if the target qubit is initially in a mixed state, since we are dealing with a linear transformation, and any mixed state can be expressed as a statistical ensemble of pure states (via the convex decomposition of a density matrix).
Thus, in general, we can express the evolution of the target qubit as^[We can also focus on the evolution of the control qubit: see the examples and exercises section **!!!TO-DO!!!**. In fact, we can choose any subset of qubits for our inputs and outputs. For example, our input could be the control qubit, and the output could be both the control and the target qubits.]

$$
  \rho\longmapsto
  \rho'= |\alpha_0|^2 \id\rho\id + |\alpha_1|^2 X\rho X
$$
where $\rho$ and $\rho'$ are the input and the output states, respectively.
We may think about this input-output relation as a mathematical representation of a quantum communication channel in which an input qubit is bit-flipped (via the operator $X$) with some prescribed probability.
But we may also take a more "global" view and see the action of the channel as arising from a unitary evolution on a larger (dilated) system, here composed of two qubits.

Our discussion can easily be extended beyond the qubits to cover any conditional dynamics of the type
$$
  U
  = \sum_i \proj{i}\otimes U_i
  =
  \begin{bmatrix}
    U_1 & 0 & 0 & \ldots
  \\0 & U_2 & 0 & \ldots
  \\0 & 0 & U_3 & \ldots
  \\\vdots & \vdots &\vdots & \ddots
  \end{bmatrix}
$$
where the vectors $\ket{i}$ form an orthonormal basis in the Hilbert space associated with a control system, and the $U_i$ are the corresponding unitary operations performed on a target system.
If the control system is prepared in state $\sum_i\alpha_i\ket{i}$ and the target in state $\ket{\psi}$, then the final state of the two systems is
$$
  \sum_i \alpha_i\ket{i}\otimes U_i\ket{\psi}
$$
and, by the same sequence of arguments as before, we obtain the evolution of the target system alone, and express it as
$$
  \rho\longmapsto
  \rho' = \sum_{i=1} p_i U_i \rho U^\dagger_i
$$
where $p_i=|\alpha_i|^2$.
That is, the state of the target system is modified by the unitary $U_i$, chosen randomly with probability $p_i$.

The reason we are paying a particular attention to the random unitaries is that each unitary is invertible, and, as such, they offer a sliver of hope for reversing the action of the channel.
If we can learn, post factum, which particular unitary operation $U_i$ was chosen then we can simply apply the inverse of that unitary and recover the original state.
For example, if we can measure the control system in the $\ket{i}$ basis, then measuring the outcome to be $k$ tells us that we have to apply $U_k^\dagger$ to the target to recover its input state.
However, if we do not have access to the control system, then there is very little we can do: *we cannot figure out which particular unitary was applied by inspecting the target system alone*.
In this case the best we can do is to apply the inverse of the most likely unitary, which will then recover the input state, *but only with some probability of success*.
In order to do better than that we have to look at slightly different channels.


### Example

A **single qubit Pauli channel** applies one of the Pauli operators, $X$, $Y$ or $Z$, chosen randomly with some prescribed probabilities $p_x$, $p_y$ and $p_z$, giving
$$
  \rho\longmapsto
  p_0 \id \rho\id + p_x X\rho X+ p_y Y\rho Y+  p_z Z\rho Z.
$$
The Pauli operators represent **quantum errors**: bit-flip $X$, phase-flip $Z$, and the composition of the two $Y=iXZ$.



## Random isometries