# Fault tolerance {#fault-tolerance}

> TO-DO

::: {.todo latex=""}
<!-- TO-DO: write this -->
<!-- TO-DO: <div class="video" title="Fault-tolerant computation and threshold theorems" data-videoid="TPUElc_4amo"></div> -->
:::









































































































<!-- ## *Remarks and exercises* {#remarks-and-exercises-fault-tolerance} -->



<!-- ### Transversal gates in more detail {#detailed-transversal-gates}

<div class="video" title="Seven-qubit code and transversal constructions" data-videoid="vZ5p_fJbTMc"></div>

As mentioned in Section \@ref(clifford-walks-on-stabiliser-states), we can achieve universal computation if we have access to the Clifford gates (controlled-$\NOT$, Hadamard, and $S=P_{\pi/2}$) and the non-Clifford gate $T=P_{\pi/4}$.
It so happens that each of these is a little bit more tricky than the previous one, but to understand what we mean by this we need to give a definition.

::: {.idea latex=""}
Suppose we're interested in some $[[n,k,d]]$ stabiliser code $\mathcal{C}$.
Let $U$ be a single-qubit unitary, representing some computational gate whose logical version $U_L$ we want to study.

- If $U^{\otimes n}$ is an implementation for $U_L$ (i.e. if its effect on the codespace is exactly the effect of logical $U$) then we say that $U$ is **strictly transversal**.

- If there exist single-qubit unitaries $V_1,\ldots,V_n$ such that $V_1\otimes\ldots\otimes V_n$ is an implementation for $U_L$, then we say that $U$ is **weakly transversal**.

It's important to note that "being transversal" isn't an intrinsic property of an operator, but depends on the code: a gate might be transversal with respect to one code but not transversal with respect to another.
:::

For our purposes, we don't really mind so much whether a gate is strictly or weakly transversal, so we'll sometimes just refer to them both as "transversal".^[This is another piece of terminology where different sources use different conventions, so it's always a good idea to check which definition of transversal is being used.]
The reason that we care about transversal gates at all (be they weak or strong) is because they are *inherently fault tolerant*.
What do we mean by this?
Well, by their very nature, if an error affects one (physical) qubit, then transversal gates *will not* propagate that error, because they involve no interaction between different (physical) qubits.
There is also the bonus that transversal gates are implemented by a single "gate step", rather than some sequential combination of gates, which also has positive implications for fault tolerance (thanks to the **threshold theorem**, which we will see in Section \@ref(putting-it-all-together)) as well as making the overall complexity generally simpler.

The next natural question to ask is this: "which of the four gates necessary for universal computation are transversal for which codes"?
As we shall see, the Steane code admits a lot of transversal gates, due to it being a particularly nice example of a CSS code, whereas the three-qubit code and (thus) the Shor code do not admit quite so many.

To begin with, we might as well say what we already know in terms of this new vocabulary.

::: {.idea latex=""}
If $\mathcal{C}$ is a CSS code, then all Pauli operators are (weakly) transversal.
:::

This is immediate by construction: implementations of the logical Pauli operators are, in particular, elements of $\mathcal{P}_n$, which are exactly $n$-fold tensor products (of Pauli operators).^[In the example of the Steane code, we saw that $X$ and $Z$ are actually *strictly* transversal. The question of when this happens forms part of Exercise \@ref(odd-parity-transversal-gates).]

For other gates, we need to do a bit more work.
Generally, to show that some operator $U$ is transversal, we need to show two things: that $U^{\otimes n}$ preserves the codespace, and then that it actually enacts the logical $U$ operation.
In order to do this, we need to understand how unitaries $V$ (such as $V=U^{\otimes n}$) actually act on stabilisers, given that we already know they act as $\ket{\psi}\mapsto V\ket{\psi}$ on states.
So say that $P\in\mathcal{S}$ is some stabiliser, and $\ket{\psi}$ is in the corresponds codespace, so that $P\ket{\psi}=\ket{\psi}$.
We can notice that
$$
  \begin{aligned}
    (VPV^\dagger)V\ket{\psi}
    &= VP(V^\dagger V)\ket{\psi}
  \\&= VP\ket{\psi}
  \\&= V\ket{\psi}
  \end{aligned}
$$
which says that $VPV^\dagger$ stabilises $V\ket{\psi}$.
In other words, unitaries act on stabilisers by conjugation: $P\mapsto VPV^\dagger$.

::: {.idea latex=""}
If $\mathcal{C}$ is a CSS code, then $\cNOT$ is (strictly) transversal.
:::

To be clear what we mean by this, we're claiming we can get a logical controlled-$\NOT$ gate on two "qubits" $q_1$ and $q_2$ by simply using controlled-$\NOT$ gates on each corresponding pair of physical qubits in the encoding:

```{r,engine='tikz',engine.opts=list(template="latex/tikz2pdf.tex"),fig.width=2.25}
\begin{quantikz}
  \lstick[wires=3]{$q_1$}
  & \ctrl{3}
  & \qw
  & \qw
  & \qw
\\& \qw
  & \ctrl{3}
  & \qw
  & \qw
\\& \qw
  & \qw
  & \ctrl{3}
  & \qw
\\\lstick[wires=3]{$q_2$}
  & \targ{}
  & \qw
  & \qw
  & \qw
  & \qw
\\& \qw
  & \targ{}
  & \qw
  & \qw
  & \qw
\\& \qw
  & \qw
  & \targ{}
  & \qw
  & \qw
\end{quantikz}
```

Let's write $\cNOT_L$ to mean this $\cNOT^{\otimes n}$, and then prove that it deserves this name.
By writing out the matrix for $\cNOT$, we see that $\cNOT^\dagger=\cNOT$, and so $\cNOT_L$ acts on stabilisers via $P\mapsto \cNOT_L P\cNOT_L$.
Since we have are working with a CSS code, we know that we can our stabiliser generators are all either of $X$-type or of $Z$-type, i.e. of the form $X_x$ or $Z_x$ where $x$ is some row of the parity check matrix.
This means that $\mathcal{S}\otimes\mathcal{S}$ is generated by four types of stabilisers: $X_x\otimes\id$, $\id\otimes X_x$, $Z_x\otimes\id$, and $\id\otimes Z_x$.
What does $\cNOT_L$ do to each of these?
Well,
$$
  \begin{aligned}
    \cNOT_L(X_x\otimes\id)\cNOT_L
    &= X_x\otimes X_x
    = (X_x\otimes\id)(\id\otimes X_x)
  \\\cNOT_L(\id\otimes X_x)\cNOT_L
    &= \id\otimes X_x
  \\\cNOT_L(Z_x\otimes\id)\cNOT_L
    &= Z_x\otimes Z_x
    = (Z_x\otimes\id)(\id\otimes Z_x)
  \\\cNOT_L(\id\otimes Z_x)\cNOT_L
    &= \id\otimes Z_x
  \end{aligned}
$$
and so it sends stabilisers to stabilisers, and thus preserves the codespace.

The only other thing we need to check is that it actually acts how a logical $\cNOT$ should act: it should be the case that^[This is an example of how it can be easier to define operators in terms of how they behave with respect to other operators, instead of how they act on states.]
$$
  \begin{aligned}
    \cNOT_L\colon
    X_L\otimes\id
    &\longmapsto X_L\otimes X_L
  \\\id\otimes X_L
    &\longmapsto \id\otimes X_L
  \\Z_L\otimes\id
    &\longmapsto Z_L\otimes \id
  \\\id\otimes Z_L
    &\longmapsto Z_L\otimes Z_L
  \end{aligned}
$$
since this is exactly how $\cNOT$ acts for $X$ and $Z$.
But this follows from exactly the same sort of argument as for the stabiliser generators.

::: {.technical title="CSS codes and controlled-NOT" latex="{CSS codes and controlled-$\NOT$}"}
The converse of the above theorem is actually true, giving us a much stronger statement: *a code is a CSS code if and only if $\cNOT$ is strictly transversal*.

We won't prove this here, but here's a sketch of how the proof would go: you can take any stabiliser, write it as a product of an $X$-type term and a $Z$-type term (and a global phase), and then use the fact that $\cNOT$ is strictly transversal to show that each of the $X$-type and $Z$-type terms are actually stabilisers; from this, you just need to pick some independent set to form a basis, so that you can write your code as generated by a bunch of $X$-type stabilisers and a bunch of $Z$-type ones, which means that it is a CSS code.
:::

This is essentially all we can say for an arbitrary CSS code: Pauli operators and controlled-$\NOT$ are transversal.
But our main example of interest has been the Steane code, which is of a very special form: it is a CSS code of a classical code over itself, namely the Hamming $[7,4,3]$ code.
We can say quite a bit more about CSS codes of this specific type.

::: {.idea latex=""}
If $\mathcal{C}=\operatorname{CSS}(C,C)$, then the Hadamard is (strictly) transversal.
:::

To prove this, we start by just writing down the action of $H^{\otimes n}$ on any stabiliser, say of $X$-type: if $x$ is some row of the parity-check matrix $H$ of the classical code $C$, then
$$
  H^{\otimes n}X_x H^{\otimes n}
  = Z_x.
$$
Since the $X$-type stabilisers come from the same code as the $Z$-type stabilisers, this says that if $X_x$ is a stabiliser then so too is $H^{\otimes n}X_x H^{\otimes n}$, which means that $H^{\otimes n}$ preserves the code space.
Again, just as before, we can also show that
$$
  \begin{aligned}
    H^{\otimes n}X_L H^{\otimes n}
    &= Z_L
  \\H^{\otimes n}Z_L H^{\otimes n}
    &= X_L
  \end{aligned}
$$
exactly as the Hadamard should act, which means that $H^{\otimes n}$ is indeed the logical Hadamard.

Here we can also see a code that *doesn't* admit a transversal Hadamard: the three-qubit code.
Recall that its logical states are
$$
  \begin{aligned}
    \ket{0}_L\
    &= \ket{000}
  \\\ket{1}_L\
    &= \ket{111}
  \end{aligned}
$$
which are *unentangled*.
Any transversal gate will, by definition, act separately on each physical qubit, which means that it will never be able to take an unentangled state to an entangled one.
But this is exactly the problem!
By definition, the logical Hadamard sends $\ket{0}_L$ to $\ket{+}_L$, and the latter state *is* entangled:^[The entangled state $\ket{+}_L$ is so important that it actually gets a special name: the **GHZ state**, for [Daniel Greenberger](https://en.wikipedia.org/wiki/Daniel_Greenberger), [Michael Horne](https://en.wikipedia.org/wiki/Michael_Horne_(physicist)), and [Anton Zeilinger](https://en.wikipedia.org/wiki/Anton_Zeilinger).]
$$
  \begin{aligned}
    \ket{+}_L
    &\coloneqq \frac{1}{\sqrt{2}}(\ket{0}_L+\ket{1}_L)
  \\&= \frac{1}{\sqrt{2}}(\ket{000}+\ket{111}).
  \end{aligned}
$$
Note that this is *not* equal to $\ket{{+}{+}{+}}$, since
$$
  \ket{{+}{+}{+}}
  = \sum_{x\in\{0,1\}^3} \ket{x}
  \neq \ket{+}_L
$$
which is not even entangled.
This highlights the fact that that, even in a repetition code, not all logical states are merely repeated copies of the physical state.

There is one other final thing is special, perhaps surprisingly, about the Steane code, and that is the *parity* of the number of qubits that it uses: $7$ is an *odd* number.

::: {.idea latex=""}
If $\mathcal{C}=\operatorname{CSS}(C,C)$ is an $n$-qubit code with $n$ odd, then the $S$ gate is (weakly) transversal.
:::

Proving this statement doesn't require any special tricks, and is a good test that you really understand what's going on, so we leave it as part of Exercise \@ref(odd-parity-transversal-gates).

::: {.idea latex=""}
If $\mathcal{C}=\operatorname{CSS}(C,C)$ is an $n$-qubit code with $n$ odd, then the $T$ gate is *not* transversal.
:::

Note first of all that the theorems we have been giving in this section have been getting only more specific, so any code satisfying the hypotheses of one theorem also satisfy those of all preceding theorems.
In other words, any $n$-qubit CSS code of the form $\operatorname{CSS}(C,C)$ with $n$ odd (such as the Steane code) is such that controlled-$\NOT$, the Hadamard, and the $S$ gate are all transversal.
We can summarise these results in a table describing which gates are transversal for the code $\operatorname{CSS}(C_1,C_2)$, with extra hypotheses increasing in strictness from left to right:

|  | no conditions | $C_1=C_2$ | $C_1=C_2$ and odd parity |
|:---:|:---:|:---:|:---:|
| $P$ | $\checkmark$ | $\checkmark$ | $\checkmark$ |
| $\cNOT$ | $\checkmark$ | $\checkmark$ | $\checkmark$ |
| $H$ |  | $\checkmark$ | $\checkmark$ |
| $S$ |  |  | $\checkmark$ |
| $T$ |  |  | $\times$ |

If the $T$ gate were also transversal, then we would have a *universal* set of gates that are *all* transversal.
This would be fantastic, but mathematics tells us that it would be just too good to be true.

::: {.idea latex=""}
**The [Eastin--Knill Theorem](https://en.wikipedia.org/wiki/Eastin–Knill_theorem).**
It is impossible for *any* quantum code to admit a transversal implementation of a universal set of gates.
:::

This theorem means that we need to find some other way of implementing the $T$ gate.
One popular method is called **magic state distillation**, which is the idea that if we can somehow prepare the "magic state" $T\ket{+}$ then we can use this to implement the $T$ gate:^[We study how this works in Exercise \@ref(using-magic-states).]

```{r,engine='tikz',engine.opts=list(template="latex/tikz2pdf.tex"),fig.width=2.5}
\begin{quantikz}
  \lstick{$T\ket{+}$}
  & \targ{}
  & \meter{} \vcw{1}
\\\lstick{$\ket{\psi}$}
  & \ctrl{-1}
  & \gate{S}
  & \qw \rstick{$T\ket{\psi}$}
\end{quantikz}
```

While this doesn't entirely fix the problem, it is easier to think of schemes that attempt to produce high-quality magic states, perhaps by making many poor-quality copies and then "distilling" a higher-quality version from them.
 -->



<!-- ### Transversal gates for odd-parity codes {#odd-parity-transversal-gates}

Let $C=(G,H)$ be a weakly self-dual code, so that we can define the CSS code $\mathcal{C}=\operatorname{CSS}(C,C)$.
Assume that $\mathcal{C}$ is an $n$-qubit code with $n$ *odd*.

1. Prove that the weight (i.e. the number of non-zero entries) of each row of $H$ must be even.
2. Prove that $X$ and $Z$ are *strictly* transversal for $\mathcal{C}$.
  What is the importance of $n$ being odd?
3. What is the effect of the operator $S^{\otimes n}$?
  Note that your answer should depend on $n$.
  *Hint: recall that $SZS^\dagger=Z$ but $SXS^\dagger=Y$, and don't forget that $Y=iXZ$ has a phase of $i$!* -->



<!-- ### Using magic states {#using-magic-states}

In Section \@ref(transversal-gates) we said that we can apply the $T$ gate using a magic state $T\ket{+}$ using the circuit below:

```{r,engine='tikz',engine.opts=list(template="latex/tikz2pdf.tex"),fig.width=2.5}
\begin{quantikz}
  \lstick{$T\ket{+}$}
  & \targ{}
  & \meter{} \vcw{1}
\\\lstick{$\ket{\psi}$}
  & \ctrl{-1}
  & \gate{S}
  & \qw \rstick{$T\ket{\psi}$}
\end{quantikz}
```

We could prove this just by following through the evolution of the circuit and checking it by hand, but this doesn't feel very insightful.
Let's show a better way to understand this circuit.

1. Prove that the following circuit does indeed have the claimed output:

```{r,engine='tikz',engine.opts=list(template="latex/tikz2pdf.tex"),fig.width=2.5}
\begin{quantikz}
  \lstick{$\ket{0}$}
  & \targ{}
  & \phase{\theta}
  & \targ{}
  & \qw \rstick{$\ket{0}$}
\\\lstick{$\ket{\psi}$}
  & \ctrl{-1}
  & \qw
  & \ctrl{-1}
  & \qw \rstick{$P_\theta\ket{\psi}$}
\end{quantikz}
```

2. Taking inspiration from the second half of Section \@ref(encoding-arbitrary-states), show that the previous circuit is equivalent to the following:

```{r,engine='tikz',engine.opts=list(template="latex/tikz2pdf.tex"),fig.width=2.5}
\begin{quantikz}
  \lstick{$\ket{0}$}
  & \targ{}
  & \phase{\theta}
  & \gate{H}
  & \meter{} \vcw{1}
\\\lstick{$\ket{\psi}$}
  & \ctrl{-1}
  & \qw
  & \qw
  & \gate{Z}
  & \qw
\end{quantikz}
```

3. By running the previous circuit backwards in time (replacing measurement with an outcome that we choose via state preparation, and vice versa), show that the following circuit gives the claimed output:

```{r,engine='tikz',engine.opts=list(template="latex/tikz2pdf.tex"),fig.width=2.5}
\begin{quantikz}
  \lstick{$P_{-\theta}\ket{+}$}
  & \targ{}
  & \meter{} \vcw{1}
\\\lstick{$P_\theta\ket{\psi}$}
  & \ctrl{-1}
  & \gate{P_{-2\theta}}
  & \qw \rstick{$\ket{\psi}$}
\end{quantikz}
```

Note that setting $\theta=-\pi/4$ gives us exactly the magic state $T$ gate circuit that we wanted.

4. The previous circuit seems to give a very general methods for applying phase gates $P_\theta$ for arbitrary $\theta$, but it is actually only useful as a method if there exists some integer $k$ such that $2^k\theta\equiv0\mod{2\pi}$. Why? -->
